version: "3"

services:
  mysqldb:
    image: mysql:latest
    networks:
      - node-network
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: wait-for mysqldb:3306 -t 40 -- npm start
    networks:
      - node-network
    environment:
      - PORT=3000
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    networks:
      - node-network
    tty: true
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

networks:
  node-network:
    driver: bridge
